// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToDoListCodeFirst.Data;

#nullable disable

namespace ToDoListCodeFirst.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241203120649_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToDoListCodeFirst.DataModel.ToDo", b =>
                {
                    b.Property<int>("taskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("taskID"));

                    b.Property<int?>("ToDoListlistId")
                        .HasColumnType("integer");

                    b.Property<string>("taskDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("taskName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("taskStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("taskID");

                    b.HasIndex("ToDoListlistId");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("ToDoListCodeFirst.DataModel.ToDoList", b =>
                {
                    b.Property<int>("listId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("listId"));

                    b.Property<int>("user")
                        .HasColumnType("integer");

                    b.HasKey("listId");

                    b.ToTable("ToDoList", (string)null);
                });

            modelBuilder.Entity("ToDoListCodeFirst.DataModel.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userID"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("userID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ToDoListCodeFirst.DataModel.ToDo", b =>
                {
                    b.HasOne("ToDoListCodeFirst.DataModel.ToDoList", null)
                        .WithMany("tasks")
                        .HasForeignKey("ToDoListlistId");
                });

            modelBuilder.Entity("ToDoListCodeFirst.DataModel.ToDoList", b =>
                {
                    b.Navigation("tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
